#ifndef IMAGE_PACKREF_H
#define  IMAGE_PACKREF_H
#define Arial_SIZE     80547
extern FONT_EXTERNAL Arial;
#define Yes_SIZE     17406
extern BITMAP_EXTERNAL Yes;
#define Stop_gray_SIZE     17406
extern BITMAP_EXTERNAL Stop_gray;
#define Stop_SIZE     17406
extern BITMAP_EXTERNAL Stop;
#define Start_gray_SIZE     17406
extern BITMAP_EXTERNAL Start_gray;
#define Start_SIZE     17406
extern BITMAP_EXTERNAL Start;
#define Standby_SIZE     259206
extern BITMAP_EXTERNAL Standby;
#define Splash_SIZE     261126
extern BITMAP_EXTERNAL Splash;
#define Reset_gray_SIZE     17406
extern BITMAP_EXTERNAL Reset_gray;
#define Reminder_SIZE     259206
extern BITMAP_EXTERNAL Reminder;
#define pumpO_SIZE     17406
extern BITMAP_EXTERNAL pumpO;
#define pumpF_SIZE     17406
extern BITMAP_EXTERNAL pumpF;
#define plusP_SIZE     12962
extern BITMAP_EXTERNAL plusP;
#define ON_gray_SIZE     17406
extern BITMAP_EXTERNAL ON_gray;
#define OFF_gray_SIZE     17406
extern BITMAP_EXTERNAL OFF_gray;
#define No_SIZE     17406
extern BITMAP_EXTERNAL No;
#define minusM_SIZE     12962
extern BITMAP_EXTERNAL minusM;
#define LED_Mode_SIZE     259206
extern BITMAP_EXTERNAL LED_Mode;
#define HomeI_SIZE     259206
extern BITMAP_EXTERNAL HomeI;
#define Home_SIZE     259206
extern BITMAP_EXTERNAL Home;
#define HF_Mode_SIZE     259206
extern BITMAP_EXTERNAL HF_Mode;
#define Days_SIZE     29766
extern BITMAP_EXTERNAL Days;
#define Code_Entry_SIZE     259206
extern BITMAP_EXTERNAL Code_Entry;
#define Clean_Mode_SIZE     259206
extern BITMAP_EXTERNAL Clean_Mode;
#define Aux_Mode_SIZE     259206
extern BITMAP_EXTERNAL Aux_Mode;
#endif